version: "3.8"
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: crypto_portfolio